# Global defaults applied to ALL microservices

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
    cache:
      type: redis

management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  retry:
    defaults:
      max-attempts: ${RETRY_MAX_ATTEMPTS:3}
      wait-duration: ${RETRY_WAIT_DURATION:500ms}
      retry-exceptions:
        - org.springframework.web.client.ResourceAccessException
        - org.springframework.web.client.HttpServerErrorException

logging:
  level:
    root: INFO

app:
  jwt:
    secret: '{cipher}8c7e0399bf55b11b6fdafacba0df562d4011bce444fee7cc8cb8372e368e5b880d8a72038be88d8b2019b14b211a8224d53024c855dce15453db6b20f5887970c3c1b25c2a71f95d7581b3a94857a72c119fc84be98c83061d11e8f5d07965ff'
    expiration: ${JWT_EXPIRATION:86400000}