server:
  port: ${USERINFO_PORT:9093}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/userdb}
    username: root
    password: '{cipher}74ffaa4a2276b45c2bb8225c17d729b631b1445c0c2de9d874db29504b955257'
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}
    defer-datasource-initialization: true
  sql:
    init:
      mode: ${SQL_INIT_MODE:ALWAYS}
      data-locations: classpath:sql/data.sql

app:
  image:
    upload-dir: ${IMAGE_UPLOAD_DIR:uploads/users}
    base-url: ${IMAGE_BASE_URL:/user/image}
