server:
  port: ${GATEWAY_PORT:8080}
spring:
  application:
    name: ${APP_NAME:api-gateway}
  config:
    import: "configserver:http://localhost:8888"
#  cloud:
#    gateway:
#      server:
#        webflux:
#          globalcors:
#            cors-configurations:
#              '[/**]':
#                allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}
#                allowed-methods: "*"
#                allowed-headers: "*"
#          discovery:
#            locator:
#              lower-case-service-id: true
#
#          routes:
#            - id: restaurant-images
#              uri: lb://restaurant-service
#              predicates:
#                - Path=/restaurant/image/**
#              filters:
#                - name: RequestRateLimiter
#                  args:
#                    key-resolver: "#{@ipKeyResolver}"
#                    redis-rate-limiter.replenishRate: ${RL_IMAGE_REPLENISH:50}
#                    redis-rate-limiter.burstCapacity: ${RL_IMAGE_BURST:100}
#
#            - id: userinfo-service
#              uri: lb://user-service
#              predicates:
#                - Path=/api/auth/**,/user/**
#              filters:
#                - name: RequestRateLimiter
#                  args:
#                    key-resolver: "#{@ipKeyResolver}"
#                    redis-rate-limiter.replenishRate: ${RL_AUTH_REPLENISH:2}
#                    redis-rate-limiter.burstCapacity: ${RL_AUTH_BURST:5}
#
#            - id: foodcatalogue-service
#              uri: lb://food-catalogue-service
#              predicates:
#                - Path=/foodCatalogue/**
#              filters:
##                - name: Retry
##                  args:
##                    retries: 3
##                    statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, SERVICE_UNAVAILABLE
##                    methods: GET
##                    backoff:
##                      firstBackoff: 100ms
##                      maxBackoff: 500ms
##                      factor: 2
##                      basedOnPreviousValue: false
#                - name: RequestRateLimiter
#                  args:
#                    key-resolver: "#{@ipKeyResolver}"
#                    redis-rate-limiter.replenishRate: ${RL_CATALOGUE_REPLENISH:10}
#                    redis-rate-limiter.burstCapacity: ${RL_CATALOGUE_BURST:20}
#
#            - id: restaurant-service
#              uri: lb://restaurant-service
#              predicates:
#                - Path=/restaurant/**
#              filters:
#                - name: RequestRateLimiter
#                  args:
#                    key-resolver: "#{@ipKeyResolver}"
#                    redis-rate-limiter.replenishRate: ${RL_RESTAURANT_REPLENISH:10}
#                    redis-rate-limiter.burstCapacity: ${RL_RESTAURANT_BURST:20}
#
#            - id: order-service
#              uri: lb://order-service
#              predicates:
#                - Path=/order/**
#              filters:
##                - name: Retry
##                  args:
##                    retries: 3
##                    statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, SERVICE_UNAVAILABLE
##                    methods: GET
##                    backoff:
##                      firstBackoff: 100ms
##                      maxBackoff: 500ms
##                      factor: 2
##                      basedOnPreviousValue: false
#                - name: RequestRateLimiter
#                  args:
#                    key-resolver: "#{@userKeyResolver}"
#                    redis-rate-limiter.replenishRate: ${RL_ORDER_REPLENISH:5}
#                    redis-rate-limiter.burstCapacity: ${RL_ORDER_BURST:10}
#
#
#  data:
#    redis:
#      host: ${REDIS_HOST:localhost}
#      port: ${REDIS_PORT:6379}
#
#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    gateway:
#      enabled: true
#
#app:
#  jwt:
#    secret: ${JWT_SECRET:9dd088e3bccaa624d01d7f7159e7a82dbec6a6094e0c6926b7445652ab05f0a2} #(siddhant@123)
#    expiration: ${JWT_EXPIRATION:86400000}  # 24 hours