#server:
#  port: 9097
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
#spring:
#  application:
#    name: ORDER-SERVICE
#  mongodb:
#    uri: mongodb://localhost:27017/orderdb
#  data:
#    mongodb:
#      repositories:
#        type: imperative


server:
  port: 9097

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

spring:
  application:
    name: ORDER-SERVICE
  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/order_db}
  data:
    mongodb:
      repositories:
        type: imperative

management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers