apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodcatalogue
  labels:
    app: foodcatalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foodcatalogue
  template:
    metadata:
      labels:
        app: foodcatalogue
    spec:
      containers:
        - name: foodcatalogue
          image: siddhant9960/fa-foodcatalogue-service:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9095
          env:
            - name: CONFIG_SERVER_URL
              value: http://config-server:8888
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka:8761/eureka
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/foodcataloguedb
            - name: REDIS_HOST
              value: redis
---
apiVersion: v1
kind: Service
metadata:
  name: foodcatalogue
spec:
  selector:
    app: foodcatalogue
  ports:
    - port: 9095
      targetPort: 9095
