apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant
  labels:
    app: restaurant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant
  template:
    metadata:
      labels:
        app: restaurant
    spec:
      containers:
        - name: restaurant
          image: siddhant9960/fa-restaurant-service:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9091
          env:
            - name: CONFIG_SERVER_URL
              value: http://config-server:8888
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka:8761/eureka
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/restaurantdb
            - name: REDIS_HOST
              value: redis
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant
spec:
  selector:
    app: restaurant
  ports:
    - port: 9091
      targetPort: 9091
